### ISSUE TITLE
Subform validator failure

### ISSUE THREAD

**Issue by CharlesRngrd** [pallets-eco/wtforms#503]
Hi,

Setting a NumberRange validator in a subform field triggers the following error :

> TypeError: '<' not supported between instances of 'FloatField' and 'int'

The same validator works well in a field from the main form.
I put my code and my traceback bellow so you can reproduce the bug :

Here is my main file :
```python
from flask import Flask, render_template, flash, redirect, url_for
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField, StringField, FieldList, FormField
from wtforms.validators import NumberRange, ValidationError


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret'


class mySubForm(FlaskForm):
    class Meta:
        csrf = False
    mySubField = FloatField(
        validators=[NumberRange(min=-100, max=100)]
    )

class myForm(FlaskForm):
    myField = FieldList(FormField(mySubForm))
    myField2 = FloatField(
        validators=[NumberRange(min=-100, max=100)]
    )
    mySubmit = SubmitField("Save")


@app.route('/', methods=['GET','POST'])
def home():
    form = myForm()

    xLabels = ["A", "B", "C", "D"]

    for x in xLabels:
        subForm = mySubForm()
        form.myField.append_entry(subForm)

    if form.validate_on_submit():
        flash("success")
        return redirect(url_for('home'))

    return render_template("draft.html", form=form)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port="5000" ,debug=True)
```

Here is my template :
```jinja
<!DOCTYPE html>
<html>
  <head>
    <style>
      .error{border-color: red;}
    </style>
  </head>
  <body>
    <div>
      <form method="POST" action="/">
        {{ form.hidden_tag() }}

        <span><br>mySubFields<br></span>
        {% for field in form.myField %}
          {% if field.mySubField.errors %}
            {{ field.mySubField(class="error") }}
            {% for error in field.mySubField.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ field.mySubField.data }}
          {% endif %}
        {% endfor %}

        <span><br>myField2<br></span>
        {% if form.myField2.errors %}
          {{ form.myField2(class="error") }}
          {% for error in form.myField2.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.myField2 }}
        {% endif %}

        <br>
        {{ form.mySubmit() }}
      </form>

      {% with messages = get_flashed_messages(with_categories=False) %}
        {% if messages %}
          {% for message in messages %}
            <p>{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

  </body>
</html>
```
```python
Traceback (most recent call last):
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\crd\Desktop\form\tuto_flask_table_form\myPackage\draft.py", line 89, in home
    if form.validate_on_submit():
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\fields\core.py", line 941, in validate
    if not subfield.validate(form):
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\fields\core.py", line 823, in validate
    return self.form.validate()
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "C:\Users\crd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wtforms\validators.py", line 134, in __call__
    if data is None or (self.min is not None and data < self.min) or \
TypeError: '<' not supported between instances of 'FloatField' and 'int'
```

**Comment by whb07** [comment]
Hi @CharlesRngrd it appears that you've found *something* but I'm not exactly clear if this is a valid issue yet. So from what I can tell you're adding more entries with this line
```python
    xLabels = ["A", "B", "C", "D"]
    for x in xLabels:
        subForm = mySubForm()
        form.myField.append_entry(subForm)
```
going to assume you are meaning to add 4 entries and then possibly add the different "xLabel" onto each one. That's all fine but the problem is that due the dynamic nature of python you're passing what you thought were passing into the correct object, isn't quite correct.

I would like to point you out to potentially using the `FieldList` this way:
```python
class myForm(FlaskForm):
    myField = FieldList(FormField(mySubForm), min_entries=4)
    myField2 = FloatField(
        validators=[NumberRange(min=-100, max=100)]
    )
    mySubmit = SubmitField("Save")
```

Please note the `min_entries` flag. When the form fields are rendered as such you get the following:
![Screen Shot 2019-07-21 at 6 44 04 PM](https://user-images.githubusercontent.com/15861355/61598168-93fae800-abe7-11e9-98be-4bf65d6ef94a.png)


Which leads to something like this from debugging:
```python
form.validate()
Out[5]: True
form.data
Out[6]: 
{'myField': [{'mySubField': 12.0},
  {'mySubField': 13.0},
  {'mySubField': -99.0},
  {'mySubField': 100.0}],
 'myField2': 33.0,
 'mySubmit': True,
 'csrf_token': 'ImI1NzhlNDY3NTU3ZTNkMGQ4ZGI5OGUzNjMzNjMxZmQxM2E2ZDkxMmQi.XTTqWA._nyFvfInmYt5uuFgT-Ia0ED5n1w'}
```

Do let me know if this helps your question out or if you think there's something else possibly going on.

**Comment by CharlesRngrd** [comment]
Finaly I solved my problem by deleting the mySubForm. I only keep myForm :

```
class myForm(FlaskForm):
    myField = FieldList(FloatField(
        validators=[NumberRange(min=-100, max=100)]
    ))
    myField2 = FloatField(
        validators=[NumberRange(min=-100, max=100)]
    )    
   mySubmit = SubmitField("Save")
```

Then I add FloatFields to the Field List like that :

```
for x in xLabels:
     form.myField.append_entry()
```
